name: Disabled Tests

on:
  push:
  pull_request:

jobs:
  skip-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "This workflow is intentionally disabled to avoid conflict"
